/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    平面001: THREE.SkinnedMesh;
    平面001_1: THREE.SkinnedMesh;
    平面001_2: THREE.SkinnedMesh;
    平面001_3: THREE.SkinnedMesh;
    Body2: THREE.SkinnedMesh;
    buggypants: THREE.SkinnedMesh;
    hair: THREE.SkinnedMesh;
    Plane: THREE.SkinnedMesh;
    Plane_1: THREE.SkinnedMesh;
    inner: THREE.SkinnedMesh;
    NurbsPath001: THREE.SkinnedMesh;
    NurbsPath001_1: THREE.SkinnedMesh;
    outerwear: THREE.SkinnedMesh;
    pants: THREE.SkinnedMesh;
    sneakers: THREE.SkinnedMesh;
    Hips: THREE.Bone;
  };
  materials: {
    HAOLAN_Body: THREE.MeshStandardMaterial;
    HAOLAN_Face: THREE.MeshStandardMaterial;
    HAOLAN_Hair: THREE.MeshPhysicalMaterial;
    Face_Transparent: THREE.MeshPhysicalMaterial;
    HOLAN_Costume: THREE.MeshPhysicalMaterial;
    sneakers_Haolan: THREE.MeshPhysicalMaterial;
  };
};

export function HaolanModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/outpput_Haolan.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <skinnedMesh
          name="平面001"
          geometry={nodes.平面001.geometry}
          material={materials.HAOLAN_Body}
          skeleton={nodes.平面001.skeleton}
          morphTargetDictionary={nodes.平面001.morphTargetDictionary}
          morphTargetInfluences={nodes.平面001.morphTargetInfluences}
        />
        <skinnedMesh
          name="平面001_1"
          geometry={nodes.平面001_1.geometry}
          material={materials.HAOLAN_Face}
          skeleton={nodes.平面001_1.skeleton}
          morphTargetDictionary={nodes.平面001_1.morphTargetDictionary}
          morphTargetInfluences={nodes.平面001_1.morphTargetInfluences}
        />
        <skinnedMesh
          name="平面001_2"
          geometry={nodes.平面001_2.geometry}
          material={materials.HAOLAN_Hair}
          skeleton={nodes.平面001_2.skeleton}
          morphTargetDictionary={nodes.平面001_2.morphTargetDictionary}
          morphTargetInfluences={nodes.平面001_2.morphTargetInfluences}
        />
        <skinnedMesh
          name="平面001_3"
          geometry={nodes.平面001_3.geometry}
          material={materials.Face_Transparent}
          skeleton={nodes.平面001_3.skeleton}
          morphTargetDictionary={nodes.平面001_3.morphTargetDictionary}
          morphTargetInfluences={nodes.平面001_3.morphTargetInfluences}
        />
      </group>
      <skinnedMesh
        name="Body2"
        geometry={nodes.Body2.geometry}
        material={materials.HAOLAN_Body}
        skeleton={nodes.Body2.skeleton}
        morphTargetDictionary={nodes.Body2.morphTargetDictionary}
        morphTargetInfluences={nodes.Body2.morphTargetInfluences}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.buggypants.geometry}
        material={materials.HOLAN_Costume}
        skeleton={nodes.buggypants.skeleton}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.hair.geometry}
        material={materials.HAOLAN_Hair}
        skeleton={nodes.hair.skeleton}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <skinnedMesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.HAOLAN_Face}
          skeleton={nodes.Plane.skeleton}
          morphTargetDictionary={nodes.Plane.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane.morphTargetInfluences}
        />
        <skinnedMesh
          name="Plane_1"
          geometry={nodes.Plane_1.geometry}
          material={materials.HOLAN_Costume}
          skeleton={nodes.Plane_1.skeleton}
          morphTargetDictionary={nodes.Plane_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_1.morphTargetInfluences}
        />
      </group>
      <skinnedMesh
        geometry={nodes.inner.geometry}
        material={materials.HOLAN_Costume}
        skeleton={nodes.inner.skeleton}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <skinnedMesh
          name="NurbsPath001"
          geometry={nodes.NurbsPath001.geometry}
          material={materials.HAOLAN_Hair}
          skeleton={nodes.NurbsPath001.skeleton}
          morphTargetDictionary={nodes.NurbsPath001.morphTargetDictionary}
          morphTargetInfluences={nodes.NurbsPath001.morphTargetInfluences}
        />
        <skinnedMesh
          name="NurbsPath001_1"
          geometry={nodes.NurbsPath001_1.geometry}
          material={materials.HOLAN_Costume}
          skeleton={nodes.NurbsPath001_1.skeleton}
          morphTargetDictionary={nodes.NurbsPath001_1.morphTargetDictionary}
          morphTargetInfluences={nodes.NurbsPath001_1.morphTargetInfluences}
        />
      </group>
      <skinnedMesh
        geometry={nodes.outerwear.geometry}
        material={materials.HOLAN_Costume}
        skeleton={nodes.outerwear.skeleton}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <skinnedMesh
        name="pants"
        geometry={nodes.pants.geometry}
        material={materials.HOLAN_Costume}
        skeleton={nodes.pants.skeleton}
        morphTargetDictionary={nodes.pants.morphTargetDictionary}
        morphTargetInfluences={nodes.pants.morphTargetInfluences}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.sneakers.geometry}
        material={materials.sneakers_Haolan}
        skeleton={nodes.sneakers.skeleton}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <primitive object={nodes.Hips} />
    </group>
  );
}

useGLTF.preload("/outpput_Haolan.glb");
