
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    # environment:
      # POSTGRES_USER: user
      # POSTGRES_PASSWORD: password
      # POSTGRES_DB: example_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

