import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import dayjs from "dayjs";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const ClothesData = api.clothes.getAll.useQuery();
  const ClothesDelete = api.clothes.delete.useMutation();
  const DeleteClothes = (id: number) => {
    try {
      ClothesDelete.mutate({ id });
    } catch (error) {
      alert(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Link href={"/clothes/new"} className="link">
          /clothes/new
        </Link>

        {/* tableにclothesを表jjj:示 */}
        <table className="table">
          <thead>
            <th>id</th>
            <th>name</th>
            <th>price</th>
            <th>Date</th>
            <th>編集</th>
            <th>削除</th>
          </thead>
          <tbody>
            {ClothesData.data &&
              ClothesData.data.map((clothe) => (
                <tr key={clothe.id}>
                  <td>{clothe.id}</td>
                  <td>{clothe.name}</td>
                  <td>{clothe.price}</td>
                  <td>{dayjs(clothe.CreatedAt).format()}</td>
                  <td>
                    <Link
                      href={"/clothes/edit/" + String(clothe.id)}
                      className="btn-primary btn"
                    >
                      編集
                    </Link>
                  </td>
                  <td>
                    <button
                      className="btn-error btn"
                      onClick={() => {
                        DeleteClothes(clothe.id);
                      }}
                    >
                      削除
                    </button>
                  </td>
                </tr>
              ))}
          </tbody>
        </table>
      </main>
    </>
  );
};

export default Home;
