
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import dayjs from "dayjs";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const ClothesData = api.clothes.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      <Link href={"/clothes/new"} className="link">/clothes/new</Link>

        {/* tableにclothesを表示 */}
        <table className="table">
          <thead>
            <th>id</th>
            <th>name</th>
            <th>price</th>
            <th>Date</th>
            <th>編集</th>
          </thead>
          <tbody>
            {ClothesData.data && ClothesData.data.map((clothe) => (
              <tr key={clothe.id}>
                <td>{clothe.id}</td>
                <td>{clothe.name}</td>
                <td>{clothe.price}</td>
                <td>{dayjs(clothe.CreatedAt).format()}</td>
                <td>
                  <Link href={"/clothers/edit/" + String(clothe.id)}>編集</Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

      </main>
    </>
  );
};

export default Home;
