

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import dayjs from "dayjs";

import { api } from "@/utils/api";
import { z } from "zod";

const ZFormValue = z.object({
  name: z.string(),
  price: z.number(),
})
const NewPage: NextPage = () => {
  const ClothesData = api.clothes.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">


      </main>
    </>
  );
};

export default NewPage;
