// Generated by Haxe 4.3.0
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/usr/local/lib/haxe/std/cpp/_std/Std.hx",
"/usr/local/lib/haxe/std/cpp/_std/haxe/Log.hx",
"?",
"Hello.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/usr/local/lib/haxe/std/cpp/_std/Std.hx",
"/usr/local/lib/haxe/std/cpp/_std/haxe/Log.hx",
"/Users/mochi/codespace/github.com/mochi-sann/sandbox/haxe/hello_world/?",
"/Users/mochi/codespace/github.com/mochi-sann/sandbox/haxe/hello_world/Hello.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Hello",
"Std",
"haxe.Log",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
