

[tasks.compile]
description = "Build"
workspace = false
command = "cargo"
args = ["build"]

[tasks.sqladd]
description = "add migration "
install_crate = { crate_name = "sqlx", binary = "sqlx", test_arg = "-h" }
workspace = false
command = "sqlx"
args = ["migrate", "add"]

[tasks.watch]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "run"]
dependencies = ["format"]

[tasks.up]
command = "docker"
args = ["compose", "up", "-d" ,"--build"]
dependencies = ["format"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]

[tasks.dev]
dependencies = [
    "up",
    "watch"
]
