

[tasks.compile]
description = "Build"
workspace = false
command = "cargo"
args = ["build"]

[tasks.sqladd]
description = "add migration "
install_crate = { crate_name = "sqlx", binary = "sqlx", test_arg = "-h" }
workspace = false
command = "sqlx"
args = ["migrate", "add"]
