[package]
name = "mochi_browser"
version = "0.1.0"
edition = "2024"

[dependencies]
cssparser = "0.35.0"
euclid = "0.22.11"
html5ever = "0.35.0"
markup5ever = "0.35.0"
markup5ever_rcdom = "0.35.0"
selectors = "0.30.0"
url = "2.5.4"
