import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  twitter: {
    card: "summary",
    site: "mochit appdir test app ",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <nav className="bg-red-500 p-4">
          <p>this is nav bar</p>
        </nav>
        <div className="max-w-prose m-auto bg-gray-300">{children}</div>
      </body>
    </html>
  );
}
