import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { createThemeContract, style } from "@vanilla-extract/css";

const hero = style({
  color: "blue",
  backgroundColor: "#ffffff",
});
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={hero}>
          <p>わーいvanilla-extract test app</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
