services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: 3.2.2
    image: web-dev
    # entrypoint: [ "bin/docker-entrypoint.sh" ]
    # command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
      - RAILS_ENV=development
      - DB_HOST=${DEV_DB_HOST}
      - DB_PORT=${DEV_DB_PORT}
      - DB_USER=${DEV_DB_USER}
      - DB_PASSWORD=${DEV_DB_PASSWORD}
    # command : rails server -b 0.0.0.0
    # depends_on:
    #   db:
    #     condition: service_healthy

  # db:
  #   image: postgres:15.4
  #   environment:
  #     - POSTGRES_USER=${DEV_DB_USER}
  #     - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   restart: always
  #   healthcheck:
  #     test: pg_isready -U postgres
  #     interval: 2s
  #     timeout: 5s
  #     retries: 30
  #

volumes:
  pg_data:
  bundle:

