require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/organization_memberships", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OrganizationMembership. As you add validations to OrganizationMembership, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrganizationMembership.create! valid_attributes
      get organization_memberships_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      organization_membership = OrganizationMembership.create! valid_attributes
      get organization_membership_url(organization_membership)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_organization_membership_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      organization_membership = OrganizationMembership.create! valid_attributes
      get edit_organization_membership_url(organization_membership)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrganizationMembership" do
        expect {
          post organization_memberships_url, params: { organization_membership: valid_attributes }
        }.to change(OrganizationMembership, :count).by(1)
      end

      it "redirects to the created organization_membership" do
        post organization_memberships_url, params: { organization_membership: valid_attributes }
        expect(response).to redirect_to(organization_membership_url(OrganizationMembership.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrganizationMembership" do
        expect {
          post organization_memberships_url, params: { organization_membership: invalid_attributes }
        }.to change(OrganizationMembership, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post organization_memberships_url, params: { organization_membership: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested organization_membership" do
        organization_membership = OrganizationMembership.create! valid_attributes
        patch organization_membership_url(organization_membership), params: { organization_membership: new_attributes }
        organization_membership.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the organization_membership" do
        organization_membership = OrganizationMembership.create! valid_attributes
        patch organization_membership_url(organization_membership), params: { organization_membership: new_attributes }
        organization_membership.reload
        expect(response).to redirect_to(organization_membership_url(organization_membership))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        organization_membership = OrganizationMembership.create! valid_attributes
        patch organization_membership_url(organization_membership), params: { organization_membership: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested organization_membership" do
      organization_membership = OrganizationMembership.create! valid_attributes
      expect {
        delete organization_membership_url(organization_membership)
      }.to change(OrganizationMembership, :count).by(-1)
    end

    it "redirects to the organization_memberships list" do
      organization_membership = OrganizationMembership.create! valid_attributes
      delete organization_membership_url(organization_membership)
      expect(response).to redirect_to(organization_memberships_url)
    end
  end
end
